### ISSUE TITLE
Failing Typescript build on survey-vue since 1.5.19

### ISSUE THREAD

**Issue by faso** [surveyjs/survey-library#2070]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
Build fails

Error message:

```
 error  in .../node_modules/survey-vue/survey.vue.d.ts

ERROR in .../node_modules/survey-vue/survey.vue.d.ts(1348,38):
1348:38 Cannot find module '../question'.
    1346 | 
    1347 | export declare class Custom extends QuestionVue<QuestionCustomModel> {
  > 1348 |     readonly contentQuestion: import("../question").Question;
         |                                      ^
    1349 | }
    1350 | 
    1351 | 

 error  in .../node_modules/survey-vue/survey.vue.d.ts

ERROR in .../node_modules/survey-vue/survey.vue.d.ts(1353,35):
1353:35 Cannot find module '../panel'.
    1351 | 
    1352 | export declare class Composite extends QuestionVue<QuestionCompositeModel> {
  > 1353 |     readonly contentPanel: import("../panel").PanelModel;
         |                                   ^
    1354 | }
    1355 | 
    1356 | 
```

### What is the expected behavior?
Build works

### How would you reproduce the current behavior (if this is a bug)?
Install `survey-vue`@1.5.19, try and build with Typescript.

* surveyjs platform (angular or react or jquery or knockout or vue): vue

**Comment by andrewtelnov** [comment]
@faso I have added types Question and PanelModel explicitly for these two classes. It should fix the issue. I have checked new generated d.ts file and it looks normal now:

```ts
export declare class Custom extends QuestionVue<QuestionCustomModel> {
    readonly contentQuestion: Question;
}


export declare class Composite extends QuestionVue<QuestionCompositeModel> {
    readonly contentPanel: PanelModel;
}

```
Thank you,
Andrew

**Comment by faso** [comment]
Thank you!

Any idea when this change will be available on npm?

**Comment by andrewtelnov** [comment]
@faso We are targeting [April 14](https://surveyjs.io/WhatsNew).
You can build the package by yourself. There is an instruction in repo ReadMe file.

Thank you,
Andrew

**Comment by faso** [comment]
Thank you!
