### ISSUE TITLE
`!` operator with async expressions causes error

### ISSUE THREAD

**Issue by mgoetz-nerdery** [surveyjs/survey-library#7268]
### Are you requesting a feature, reporting a bug or asking a question?
Reporting a bug

### What is the current behavior?
When using the `!` operator on an async expression, the page errors out with "`this.returnResult` is not a function."
<img width="760" alt="Screenshot 2023-10-31 at 8 56 42 AM" src="https://github.com/surveyjs/survey-library/assets/32200555/3a7ef891-2304-4162-918f-ec93d3c22a97">

### What is the expected behavior?
The page should not error out, and should work as expected.

### How would you reproduce the current behavior (if this is a bug)?
1. Create a custom function that returns a value (using this.returnResult)
2. Register it to FunctionFactory as an async function (third parameter set to `true`)
3. Use this function in an expression such as `visibleIf`, and use the `!` operator to negate it.
4. Observe the failure.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://codesandbox.io/s/brave-heyrovsky-3rzmnc?file=/src/SurveyComponent.jsx

### Specify your

* browser: Google Chrome
* browser version: 117
* surveyjs platform (angular or react or jquery or knockout or vue): React
* surveyjs version: 1.9.114

**Comment by JaneSjs** [comment]
Hello @mgoetz-nerdery,

Thank you for sharing a demo. From what I gather, you placed an exclamation mark before your custom function to invert the custom function's result.

We will investigate this issue and provide you with an update shortly.

**Comment by mgoetz-nerdery** [comment]
Confirmed that this is resolved in my test case when I update to 1.9.115.  Thanks for the fast turnaround!
