### ISSUE TITLE
Error after updating to 1.5 version

### ISSUE THREAD

**Issue by sanda-au** [surveyjs/survey-library#2053]
### Are you requesting a feature, reporting a bug or asking a question?
bug

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```
your_code_here

```

 "survey-angular": "^1.5.16",
    "survey-knockout": "1.5.16",
    "survey-pdf": "^1.5.16",
    "surveyjs-editor": "1.1.25",
    "surveyjs-widgets": "^1.5.16",

core.js:6014 ERROR TypeError: Unable to process binding "if: function(){return $data.survey }"
Message: Unable to process binding "template: function(){return { name:'survey-content',data:survey,afterRender:$parent.koEventAfterRender} }"
Message: Cannot read property 'fire' of undefined
    at SurveyLiveTester.koEventAfterRender (surveyeditor.js:15182)
    at Object.G (knockout-latest.js:41)
    at e (knockout-latest.js:126)
    at a.$.Sa (knockout-latest.js:127)
    at Function.yd (knockout-latest.js:55)
    at Function.zd (knockout-latest.js:55)
    at Function.ha (knockout-latest.js:54)
    at Object.a.o.a.$ (knockout-latest.js:52)
    at Object.a.dc (knockout-latest.js:127)
    at update (knockout-latest.js:131)
### Specify your

* browser:
chrome
* browser version:
* surveyjs platform (angular or react or jquery or knockout or vue):
angular 8
* surveyjs version:
