### ISSUE TITLE
Angular compile-time error: survey-angular has no exported member 'Model'

### ISSUE THREAD

**Issue by RomanTsukanov** [surveyjs/survey-library#4051]
> ERROR in src/app/app.component.ts:2:10 - error TS2305: Module '"../../node_modules/survey-angular/survey.angular"' has no exported member 'Model'.
> import { Model, StylesManager, SurveyNG } from "survey-angular";

The error appears in v1.9.14. Worked fine in v1.9.7.

**Comment by andrewtelnov** [comment]
@RomanTsukanov Should work in v1.9.15

Thank you,
Andrew
