### ISSUE TITLE
BC break between 1.9.27 & 1.9.29 - TypeError: this.popup.unmountPopupContainer is not a function

### ISSUE THREAD

**Issue by vitexikora** [surveyjs/survey-library#4338]
### Are you requesting a feature, reporting a bug or asking a question?
Bug, and warning to other users, that may encounter it.

### What is the current behavior?
survey-react@1.9.27 does not work with survey-react-ui@1.9.29
function destroyPopupContainer was renamed to unmountPopupContainer

This had heavily broke several our apps on production, since installation of survey-react@1.9.27 (with a fixed version like this) installed an incompatible version of survey-react-ui.

### What is the expected behavior?
Following semver in case of a BC break.

### How would you reproduce the current behavior (if this is a bug)?
`npm i survey-analytics@1.9.27 survey-core@1.9.27 survey-creator-react@1.9.27 survey-react@1.9.27` and try to work with them. It crashes upon adding new elements in the creator.

**Comment by andrewtelnov** [comment]
@vitexikora You don't need "survey-react" package. You shold use "suvey-react-ui" in your case.
You currently have two instances of react survey libraries in your app.

Thank,
Andrew
