### ISSUE TITLE
1.9.14 no longer builds with typescript, "missing Survey.Model"

### ISSUE THREAD

**Issue by AntonOfTheWoods** [surveyjs/survey-library#4036]
### Are you requesting a feature, reporting a bug or asking a question?
Bug. It looks like types have been changed, and no longer correspond to the documentation.

### What is the current behavior?
Fails to build with TS after updating from 1.9.12 to 1.9.14

```
TS2339: Property 'Model' does not exist on type 'typeof import("/home/anton/.../node_modules/survey-react/survey.react")'.
```

### What is the expected behavior?
To build without error

### How would you reproduce the current behavior (if this is a bug)?
Try and use with TS

#### Provide the test code and the tested page URL (if applicable)

Test code

```
const model = new Survey.Model(modelObjects);

```

### Specify your

* surveyjs platform (angular or react or jquery or knockout or vue): react
* surveyjs version: survey-react 1.9.14

**Comment by andrewtelnov** [comment]
@AntonOfTheWoods Yes, our d.ts generator failed and it doesn't produce the following line:
`export { SurveyModel as Model };`  for survey.angular.d.ts file.
As a quick fix, please use `Survey.SurveyModel` instead of `Survey.Model`
I have already fixed our d.ts generator and it should be fine in v1.9.15

Thank you,
Andrew
